### PR TITLE
Add Minikube based dev env instructions

### PR DESCRIPTION
**Pull request by russellb**

### CODE REVIEW

**Comment by russellb** [comment]
@mhrivnak This seemed to work, except I didn't see the actuator claim the BareMetalHost.  I'm assuming that's due to the same issue you saw earlier, where our current version of cluster-api was requiring a Cluster.  I'll wait for the cluster-api update to try it again.  The instructions are probably OK, though.

**Comment by mhrivnak** [comment]
> @mhrivnak This seemed to work, except I didn't see the actuator claim the BareMetalHost. I'm assuming that's due to the same issue you saw earlier, where our current version of cluster-api was requiring a Cluster. I'll wait for the cluster-api update to try it again. The instructions are probably OK, though.

Agreed. There's also still the problem that it's trying to connect to ironic to get an image checksum, so unless you have that running and available, it will fail.

**Comment by russellb** [comment]
Thanks, Michael.  I applied your suggestions.

**Comment by prankul88** [comment]
HI @russellb , I have been trying to setup my cluster api environment on bare metal. I followed the link https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/docs/dev/minikube.md

I have applied all the CRD's mentioned in the doc

But "make run" command is stuck at 

> operator-sdk up local \
	--namespace=metal3 \
	--operator-flags="-dev"
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace metal3.                      
2019-06-12T11:44:43.954+0530	INFO	cmd	Go Version: go1.12.5
2019-06-12T11:44:43.954+0530	INFO	cmd	Go OS/Arch: linux/amd64
2019-06-12T11:44:43.954+0530	INFO	cmd	Version of operator-sdk: v0.4.0+git
2019-06-12T11:44:43.956+0530	INFO	leader	Trying to become the leader.
2019-06-12T11:44:43.956+0530	INFO	leader	Skipping leader election; not running in a cluster.
2019-06-12T11:44:44.008+0530	INFO	cmd	Registering Components.
2019-06-12T11:44:44.008+0530	INFO	kubebuilder.controller	Starting EventSource	{"controller": "metal3-baremetalhost-controller", "source": "kind source: /, Kind="}
2019-06-12T11:44:44.008+0530	INFO	kubebuilder.controller	Starting EventSource	{"controller": "metal3-baremetalhost-controller", "source": "kind source: /, Kind="}
2019-06-12T11:44:44.008+0530	INFO	cmd	Starting the Cmd.
2019-06-12T11:44:44.108+0530	INFO	kubebuilder.controller	Starting Controller	{"controller": "metal3-baremetalhost-controller"}
2019-06-12T11:44:44.209+0530	INFO	kubebuilder.controller	Starting workers	{"controller": "metal3-baremetalhost-controller", "worker count": 1}


Can you please help me debug this.

**Comment by dhellmann** [comment]
@prankul88 When you say "is stuck at" do you mean it is failing? Because "make run" will block while the operator runs in the foreground.

**Comment by prankul88** [comment]
Hi @dhellmann , thanks for replying. By stuck I mean, I expected the command to finish, but it did nothing after 

> {"level":"info","ts":1560335821.304312,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"metal3-baremetalhost-controller","worker count":1}

But later realised that I misunderstood a step in the installation guide but am still facing similar problem. 
Would be very helpful if you could take a look to this issue. [https://github.com/metal3-io/cluster-api-provider-baremetal/issues/85](url)

**Pull request merged**
