### PR TITLE
Saves a host when it's assigned a new MachineRef

### PR DESCRIPTION
**Pull request by mhrivnak**
Apparently this regressed at some point.

### CODE REVIEW

**Comment by russellb** [comment]
@mhrivnak did you consider adding a test case?

**Comment by mhrivnak** [comment]
> @mhrivnak did you consider adding a test case?

Yep, already working on that. Happy to submit them together or separate. I discovered this while getting ready for the demo, so just wanted to get that fix submitted. I can push a test to this branch if you want to wait a bit.

**Comment by russellb** [comment]
Yeah, can just wait a bit.

**Pull request merged**
